### ISSUE TITLE
Enabling experimental naming conventions

### ISSUE THREAD

**Issue by DizzyDeveloper** [arangodb/arangodb-docker#105]
Hi, 

I was wander if it is possible to enable the `extended-names-databases` feature?

Is there a way to enable it via an environment variable or a parameter of sorts? Or would I have to create a derived image with that flag set myself?

**Comment by dothebart** [comment]
Hi, 
ArangoDB configuration variables translate to CLI arguments. Hence starting the docker container with 
```
--database.extended-names-databases true
```
would be similar to 
```
[database]
extended-names-databases = true
```

**Comment by DizzyDeveloper** [comment]
@dothebart Legend thanks mate! Got it to work :)

For those who come across this later, or for a summary for myself for when I inevitably forget. Usage as follows:

docker:

```bash
docker run --name arangodb-experimental -d -p 8529:8529 -e ARANGO_ROOT_PASSWORD=1 arangodb:latest --database.extended-names-databases true
```

docker-compose:
```yaml

version: '3.9'
services:
  arangodb-experimental:
    image: arangodb:latest
    command: --database.extended-names-databases true    
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=1

```
