### ISSUE TITLE
Please provide a way to set JWT_SECRET via Environment Variable

### ISSUE THREAD

**Issue by cbluth** [arangodb/arangodb-docker#64]
I run arangodb with the docker image.
I would like to set the `JWT_SECRET` via environment variable, instead of having to do this:
```
    spec:
      containers:
      - args:
        - arangod
        - --server.jwt-secret
        - <jwt_secret_string>
```
